name: Trigger auto deployment for Azure Container App

on:
  push:
    branches: 
      [ main-p2p ] 
    paths:
      - '**'
      - '.github/workflows/deploy.yml'

  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write
      contents: read
      packages: write # Required to push to GitHub Container Registry

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to GitHub Container Registry (GHCR)
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build Docker Images
      - name: Build Docker Images
        run: |
          docker build -t ghcr.io/${{ github.repository }}/your-image-name:${{ github.sha }} .

      # Push Docker Images to GHCR
      - name: Push Docker Images
        run: |
          docker push ghcr.io/${{ github.repository }}/your-image-name:${{ github.sha }}

      # Deploy to Azure Container Apps
      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: your-container-app-name
          resourceGroup: your-resource-group
          imageToBuild: ghcr.io/${{ github.repository }}/your-image-name:${{ github.sha }}
          registryUrl: ghcr.io
          registryUsername: ${{ github.actor }}
          registryPassword: ${{ secrets.GITHUB_TOKEN }}
